H4ISH 18 card container
hack4impact-utk/second-harvest-map pull request #15
Opened 2021-03-18 00:40 UTC by huncfut

The final structure of both FoodPantryContainer and FoodPantryDisplay will change later, as we decide how it is supposed to work. For now both are working and ready for future development.

2021-03-19 03:50 UTC, huncfut commented
I made a new commit. I will try to find a way to always load the component I am working on, so I get the lint errors.

2021-03-19 23:36 UTC, VishalAiely requested changes
Overall this is a great PR! 👍 The logic of your implementation is really easy to follow and does everything detailed in the issue on Jira. Most of the comments I left are to remove some warns (adding return types) and some small fixes.
Thanks for getting this done so quickly after the dev meeting!

Fix before Merge:
- Make sure to change `renderPagination` to use ternary and always return JSX
- Also make sure to call `renderPagination` in the render function

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryContainer/index.tsx
> +    <div>
I prefer using React Fragments (`<>` and `</>`) for wrapping components to have less nesting in the rendered DOM, but its not a big deal to leave the divs

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +  onPageChange = (event: React.ChangeEvent<unknown>, page: number) => {
Add return type to remove warning
```suggestion
  onPageChange = (event: React.ChangeEvent<unknown>, page: number): void => {
```

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +  getPantriesToDisplay = () => {
The function is a very simple and elegant way of doing this 👍
- Sidenote: add return type for warning suppression
```suggestion
  getPantriesToDisplay = (): FoodPantry[] => {
```

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +    const pageCount: number = pantries.length - 3 > 0 ? pantries.length - 3 : 1;
No need for explicit type annotation in this instance
```suggestion
    const pageCount = pantries.length - 3 > 0 ? pantries.length - 3 : 1;
```

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +    return pageCount > 1 && <Pagination page={offset + 1} count={pageCount} onChange={this.onPageChange} />;
Just to keep the function more consistent, I suggest changing this to a ternary statement where empty JSX is returned (to maintain single return type, currently this returns `false` | `JSX.Element`)

```suggestion
    return pageCount > 1 ? <Pagination page={offset + 1} count={pageCount} onChange={this.onPageChange} /> : <></>;
```

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +  renderPagination = () => {
```suggestion
  renderPagination = (): JSX.Element => {
```

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +  render() {
```suggestion
  render(): JSX.Element {
```

2021-03-19 23:36 UTC, VishalAiely commented on src/components/FoodPantryDisplay/index.tsx
> +        {this.renderPagination}
I think this should be called rather than just having the function here
```suggestion
        {this.renderPagination()}
```

2021-03-22 15:24 UTC, VishalAiely approved these changes

2021-03-24 18:23 UTC, merged